---
- name: fetch the python app into src dir
  git: >-
    repo={{ python_app_git_repo }}
    dest={{ python_app_deployment_dir }}/src
    version={{ python_app_git_version }}
    depth=1
    umask=0022
  become: true
  become_user: "{{ python_app_user }}"
  register: git_app

- name: determine virtualenv command
  set_fact:
    virtualenv_command: "{{ (python_app_python_version[0] == '3') | ternary('pyvenv', 'virtualenv') }}"

- name: install app dependencies into virtualenv
  pip: >-
    virtualenv={{ python_app_deployment_dir }}/virtualenv
    virtualenv_command={{ python_app_python_bin }}/{{ virtualenv_command }}
    requirements={{ python_app_deployment_dir }}/src/{{ python_app_requirements_txt }}
    umask=0022
    state=present
  become: true
  become_user: "{{ python_app_user }}"
