---
- name: Converge
  hosts: all
  roles:
    - role: datagov-deploy-python-app
      vars:
        python_app_user: app
        python_app_git_repo: https://github.com/GSA/pycsw.git
        python_app_deploy_version: "20190308132800"
        python_app_python_version: "3.6.8"
        python_app_os_packages:
          - libgeos-dev
        python_app_systemd_files:
          - "{{ playbook_dir }}/files/pycsw-load.service"
        python_app_supervisor_file: "{{ playbook_dir }}/files/pycsw.conf"
        python_app_crontab: "{{ playbook_dir }}/files/crontab"
